### ISSUE TITLE
Use of Bismark output for imputation

### ISSUE THREAD

**Issue by AST87** [gdewael/cpg-transformer#5]
Hi Gaetan,
CpG-transformer is a great tool. I have been analyzing single-cell BSC data (from NMT-seq) and would like to impute some of the missing CpGs. However, I am unable to figure out a way to use cpg-transformer on bismark output file. I tried FastatoTable function on raw data to prepare input files but it gets complicated for paired-end sequencing.

Could you please suggest a way by which I could use the output from bismark as input to cpg-transformer? If not, could you please suggest how to use the imputed output from raw data in Bismark?

**Comment by gdewael** [comment]
Hi, thanks for your interest in using CpG Transformer!

I am not a specialist in using Bismark, but I think you should be able to get a single CpG methylation file for every cell. (Look for the "Bismark methylation extractor" steps [here](http://felixkrueger.github.io/Bismark/Docs/)).

Then, from these Bismark output files, you should try to construct a tab-separated file that looks like [this](https://github.com/gdewael/cpg-transformer/tree/main/data#from-tsv-files). Where every row indicates a CpG Site, and every column with -1s, 0s, and 1s indicates a cell. This will require some manual programming, as I am not sure an automated script (from bismark to this tsv format) is a good choice as users may have wildly different experimental settings and needs.

Once you have this script, you can use our provided functions `EncodeFromTsv.py` to encode the methylation calls and `EncodeGenome.py` to encode the genome to NumPy formats for input to the model.

Let me know if this answers your questions!

**Comment by AST87** [comment]
Thank you Gaetan for the solution.
